website/blog/urls.py
from django.conf.urls import url
from .import views
from blog.models import Entry
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
app_name = 'blog'

info_dict = {
    'queryset': Entry.objects.all(),
    'date_field': 'pub_date',
}

urlpatterns = [
    # 主页 http://127.0.0.1/blog/
    url(r'^$', views.index, name='blog_index'),
    url(r'^(?P<blog_id>[0-9]+)/$', views.detail, name='blog_detail'),
    #http://127.0.0.1/blog/category/2
    url(r'^category/(?P<category_id>[0-9]+)/$', views.category,name='blog_category'),
    url(r'^archives/(?P<year>[0-9]+)/(?P<month>[0-9]+)$', views.archives,name='blog_archives'),
    url(r'^tag/(?P<tag_id>[0-9]+)/$', views.tag,name='blog_tag'),
    url(r'^search/$', views.search,name='blog_search'),
    url(r'^reply/(?P<comment_id>\d+)/$', views.reply, name='comment_reply'),
    url(r'^sitemap.xml$', sitemap,
        {'sitemaps': {'blog': GenericSitemap(info_dict, priority=0.6)}},
        name='django.contrib.sitemaps.views.sitemap'),
]

website/website/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from blog.feed import LatestEntriesFeed
from blog import views as blog_views
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from blog.models import Entry

info_dict ={
    'queryset': Entry.objects.all(),
    'date_field': 'modified_time'
}
urlpatterns = [
    url(r'^$',blog_views.index),
    url(r'^admin/', admin.site.urls),
    url(r'^blog/',include('blog.urls')),
    url(r'^login/$', blog_views.blog_login),
    url(r'^logout/$', blog_views.blog_logout),
    url(r'^register/',blog_views.register),
    url(r'^latest/feed/$',LatestEntriesFeed()),
    url(r'^comments/',include('django_comments.urls')),
    url(r'^sitemap\.xml$',sitemap,{'sitemaps':{'blog': GenericSitemap(info_dict,priority=0.6)}},name='django.contrib.sitemaps.views.sitemap'),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

handler403 = blog_views.permission_denied
handler404 = blog_views.page_not_found
handler500 = blog_views.page_error

website/blog/models.py
from django.db import models
from django.urls import  reverse
# Create your models here.
class Category(models.Model):

    name = models.CharField(max_length=128 , verbose_name='博客分类')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "博客分类"
        verbose_name_plural = '博客分类'

class Tag(models.Model):

    name = models.CharField(max_length=128 , verbose_name='博客标签')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "博客标签"
        verbose_name_plural = '博客标签'

class User(models.Model):

    gender=(
        ('male',"男"),
        ('female',"女")
            )
    name = models.CharField(max_length=128, unique=True, verbose_name="姓名")
    password = models.CharField(max_length=256, verbose_name="密码")
    email = models.EmailField(unique=True,null=True,verbose_name="邮箱")
    sex = models.CharField(max_length=32,choices=gender,default='男')
    c_time = models.DateTimeField(auto_now_add=True,verbose_name="创建时间")

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["-c_time"]
        verbose_name = "用户"
        verbose_name_plural = "用户"

class Entry(models.Model):

    title = models.CharField(max_length=128 , verbose_name='文章标题')

    author = models.ForeignKey(User,verbose_name='博客作者',null=True, blank=True, on_delete=models.SET_NULL)

    img = models.ImageField(upload_to='blog_images', null=True, blank=True, verbose_name='博客配图')

    body = models.TextField(verbose_name='博客正文')

    abstract = models.TextField(max_length=256,blank=True,null=True, verbose_name='博客摘要')

    visiting = models.PositiveIntegerField(default=0, verbose_name='博客访问量')

    category = models.ManyToManyField('Category',verbose_name='博客分类')

    tags = models.ManyToManyField('Tag',verbose_name='博客标签')

    created_time = models.DateTimeField(auto_now_add=True , verbose_name='创建时间')

    modified_time = models.DateTimeField(auto_now=True, verbose_name='修改时间')

    def __str__(self):
        return  self.title

    def get_absolute_url(self):
        return reverse('blog:blog_detail',kwargs={'blog_id':self.id}) #http://127.0.0.1/blog/3

    def increase_visiting(self):
        self.visiting +=1
        self.save(update_fields=['visiting'])

    class Meta:
        ordering = ['-created_time']
        verbose_name = '博客'
        verbose_name_plural = '博客'

website/blog/forms.py
from django import forms

class UserForm(forms.Form):
    username = forms.CharField(label="用户名", max_length=128, widget=forms.TextInput(attrs={'class':'form-control'}))
    password = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput(attrs={'class':'form-control'}))

class RegisterForm(forms.Form):
    gender=(
        ('male',"男"),
        ('female',"女")
            )
    username = forms.CharField(label="用户名", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label="确认密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label="邮箱地址",widget=forms.EmailInput(attrs={'class': 'form-control'}))
    sex = forms.ChoiceField(label='性别',choices=gender)

website/blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .import models
import markdown
import pygments
from django.db.models import Q
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django_comments.models import Comment
from django_comments import models as comment_models
from .import forms
from django.contrib.auth import authenticate,login,logout


def make_paginator(objects, page, num = 5):
    '''
    生成分页器函数
    :param objects:
    :param page:
    :param num:
    :return:
    '''
    paginator = Paginator(objects ,num)
    try:
        object_list = paginator.page(page)
    except PageNotAnInteger:
        object_list = paginator.page(1)
    except EmptyPage:
        object_list = paginator.page(paginator.num_pages)
    return object_list,paginator


def pagination_data(paginator ,page):
    '''
    用于自定义展示分页页码的方法
    :param paginator: Paginator类的对象
    :param page: 当前请求的页码
    :return: 一个包含所有页码和符号的字典
    '''
    if paginator.num_pages == 1:
        return {}
    left = []
    right = []
    left_has_more = False
    right_has_more = False
    first = False
    last = False
    #获得用户当前请求的页码号
    try:
        page_number = int(page)
    except ValueError:
        page_number = 1
    except:
        page_number = 1

    total_pages = paginator.num_pages
    page_range = paginator.page_range

    if page_number ==1:
        right =page_range[page_number:page_number+4]

        if right[-1]< total_pages-1:
            right_has_more=True
        if right[-1]<total_pages:
            last =True
    elif page_number == total_pages:
        left = page_range[(page_number-3) if(page_number-3)>0 else 0:page_number-1]
        if left[0]>2:
            left_has_more=True
        if left[0]>1:
            first = True
    else:
        left = page_range[(page_number-3)if (page_number - 3)>0 else 0:page_number-1]
        right = page_range[page_number:page_number+2]

        if right[-1]<total_pages-1:
            right_has_more=True
        if right[-1]<total_pages:
            last = True
        if left[0]>2:
            left_has_more =True
        if left[0]>1:
            first = True
    data = {
        'left':left,
        'right':right,
        'left_has_more':left_has_more,
        'right_has_more':right_has_more,
        'first':first,
        'last':last,
    }
    return data

def index(request):
    entries = models.Entry.objects.all()
    page = request.GET.get('page',1)
    entry_list,paginator = make_paginator(entries, page)
    page_data = pagination_data(paginator, page)

    return render(request, 'blog/index.html',locals())

def detail(request,blog_id):
    #entry = models.Entry.objects.get(id = blog_id )
    entry = get_object_or_404(models.Entry, id=blog_id)
    md = markdown.Markdown(extensions=['markdown.extensions.extra',
                                       'markdown.extensions.codehilite',
                                       'markdown.extensions.toc'
                                       ])
    entry.body = md.convert(entry.body)
    entry.toc = md.toc #目录信息
    entry.increase_visiting()

    comment_list = list()

    def get_comment_list(comments):
        for comment in comments:
            comment_list.append(comment)
            children = comment.child_comment.all()
            if len(children)>0:
                get_comment_list(children)

    top_comments = Comment.objects.filter(object_pk= blog_id , parent_comment=None ,content_type__app_label='blog').order_by('-submit_date')
    get_comment_list(top_comments)
    return render(request, 'blog/detail.html',locals())

def category(request, category_id):
    #c = models.Category.objects.get( id=category_id )
    c = get_object_or_404(models.Category, id = category_id)
    entries = models.Entry.objects.filter(category = c)
    page = request.GET.get('page',1)
    entry_list, paginator = make_paginator(entries,page)
    page_data = pagination_data(paginator,page)
    return render(request,'blog/index.html',locals())

def tag(request,tag_id):
    # t = models.Tag.objects.get(id=tag_id)
    t = get_object_or_404(models.Tag, id=tag_id)
    if t.name =="全部":
        entries = models.Entry.objects.all()
    else:
        entries = models.Entry.objects.filter(tags=t)
    page = request.GET.get('page', 1)
    entry_list, paginator = make_paginator(entries, page)
    page_data = pagination_data(paginator, page)
    return render(request, 'blog/index.html', locals())

def search(request):
    '''
    关键词搜索
    :param request:
    :return:
    '''

    keyword = request.GET.get('keyword',None)
    if not keyword:
        error_msg = "请输入关键字"
        return render(request,'/blog/index.html',locals())

    entries = models.Entry.objects.filter(Q(title__icontains=keyword)
                                         |Q(body__icontains=keyword)
                                         |Q(abstract__icontains=keyword))
    page = request.GET.get('page', 1)
    entry_list, paginator = make_paginator(entries, page)
    page_data = pagination_data(paginator, page)
    return render(request, 'blog/index.html', locals())

def archives(request, year, month):
    entries = models.Entry.objects.filter(created_time__year=year,created_time__month=month)
    page = request.GET.get('page', 1)
    entry_list, paginator = make_paginator(entries, page)
    page_data = pagination_data(paginator, page)
    return render(request, 'blog/index.html', locals())

def permission_denied(request):
    return render(request , 'blog/403.html',locals())

def page_not_found(request):
    return render(request, 'blog/404.html', locals())

def page_error(request):
    return render(request, 'blog/500.html', locals())

def reply(request,comment_id):
    if not request.session.get('login',None) and not request.user.is_authenticated():
        return redirect('/')
    parent_comment = get_object_or_404(comment_models.Comment, id = comment_id)
    return  render(request ,'blog/reply.html',locals())

def blog_login(request):
    #避免重复登录
    if request.session.get('is_login',None):
        return redirect("blog:blog_index")

    if request.method == "GET":
        #记录登录请求来源的url,如果没有设置为首页
        request.session['login_from'] = request.META.get('HTTP_REFERER','/')
        login_form = forms.UserForm()
        return render(request, 'blog/login.html',locals())

    if request.method == "POST":
        login_form = forms.UserForm(request.POST)
        message = '请检查填写的内容！'
        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            auth_user = authenticate(username= username,password=password)
            if auth_user is not None:
                # 首先验证django认证系统的用户
                login(request, auth_user)
                request.session['is_login'] = True
                request.session['user_name'] = username
                return redirect(request.session['login_from']) #登录成功 重定向到登录请求url
            #其次验证models.User模型数据
            try:
                user = models.User.objects.get(name=username)
                if user.password == password:
                    request.session['is_login'] = True
                    request.session['user_name'] = user.name
                    return redirect(request.session['login_from'])  # 登录成功 重定向到登录请求url
                else:
                    message = "密码不正确！"
            except:
                    message = "认证用户密码错误或用户不存在！"
            return render(request,'blog/login.html',locals())

    login_form = forms.UserForm
    return render(request, 'blog/login.html',locals())

def blog_logout(request):
    if request.user.is_authenticated:
        logout(request)
    else:
        request.session.flush()
    return redirect("blog:blog_index")

def register(request):
    if request.session.get('is_login',None):
        #登录状态无法注册
        return redirect("blog:blog_index")

    if request.method =="POST":
        register_form = forms.RegisterForm(request.POST)
        message = "请检查填写的内容！"
        if register_form.is_valid():
            username = register_form.cleaned_data['username']
            password1 = register_form.cleaned_data['password1']
            password2 = register_form.cleaned_data['password2']
            email = register_form.cleaned_data['email']
            sex = register_form.cleaned_data['sex']
            if password1 != password2:
                message = "两次输入的密码不同！"
                return render(request, 'blog/register.html',locals())
            else:
                same_name_user = models.User.objects.filter(name= username)
                if same_name_user: #用户名唯一
                    message = '用户名已经存在，请重新选择用户名！'
                    return render(request, 'blog/register.html',locals())
                same_email_user = models.User.objects.filter(email=email)
                if same_email_user:  # 邮箱地址唯一
                    message = '该邮箱地址已被注册，请使用别的邮箱！'
                    return render(request, 'blog/register.html', locals())

                # 当一切都OK的情况下，创建新用户
                new_user = models.User()
                new_user.name = username
                new_user.password = password1
                new_user.email = email
                new_user.sex = sex
                new_user.save()
                return redirect('/login/')  # 注册成功！自动跳转到登录页面

    register_form =forms.RegisterForm()
    return render(request, 'blog/register.html',locals())

# def login(request):
#     import requests
#     import json
#     from django.conf import settings
#     code = request.GET.get('code', None)
#     if code is None:
#         return redirect('/')
#
#     access_token_url = 'https://api.weibo.com/oauth2/authorize?client_id=%s&client_secret=%s&grant_type=authorization_code&redirect_uri=http://www.yoursite.com/login&code=%s'\
#                         %(settings.CLIENT_ID, settings.APP_SECRET, code)
#
#     ret = requests.post(access_token_url)
#     data = ret.text

website/blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>{% block title %}基本模板{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'blog/css/blog_nav.css' %}" rel="stylesheet">
    {% block css %}
    {% endblock %}
    <!-- HTML5 shim 和 Respond.js 是为了让 IE8 支持 HTML5 元素和媒体查询（media queries）功能 -->
    <!-- 警告：通过 file:// 协议（就是直接将 html 页面拖拽到浏览器中）访问页面时 Respond.js 不起作用 -->
    <!--[if lt IE 9]>
      <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
      <nav class="navbar navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#my-nav" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><img src="{% static 'blog/images/blog_test.jpg' %}"/><span class="navbar-text">我的博客</span></a>
        </div>

        <!-- Collect the nav links, forms, and other c ontent for toggling -->
        <div class="collapse navbar-collapse" id="my-nav">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/blog/">博客</a></li>
            <li ><a href="#">关于博主</a></li>
            <li ><a href="#">联系我们</a></li>
          </ul>
          <form class="navbar-form navbar-left" action="{% url 'blog:blog_search' %}" method="get">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search" name="keyword">
            </div>
            <button type="submit" class="btn btn-default" >搜索</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
              {% if request.session.is_login %}
                  <li><h4>当前在线：{{ request.session.user_name }}</h4></li>
                  <li><a href="/logout/"><i class="glyphicon glyphicon-log-out"></i>注销</a></li>
              {% else %}
                <li>
                    {#<a href="https://api.weibo.com/oauth2/authorize?client_id=4141240961&response_type=code&redirect_uri=http://www.yoursite.com/login/?next={{ request.path }}"><i class="glyphicon glyphicon-log-in"></i>&nbsp;&nbsp;登录</a>  #}
                    <a href="/login/"><i class="glyphicon glyphicon-log-in"></i>登录</a>
                </li>
                  <li>
                    <a href="/register/"><i class="glyphicon glyphicon-registration-mark">注册</i></a>
                  </li>
              {% endif %}
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    {% block content %}

    {% endblock %}
     <div id ="back-to-top">
          <i class="glyphicon glyphicon-arrow-up"></i>
     </div>
      <footer>
        <div class="footer" role="navigation">
            <div class="container">
                <div class="navbar-text">
                    <ul class="footer-text">
                        <li><a href="#">主页</a></li>
                        <li><a href="#" target="_blank">联系我们</a></li>
                        <li><a href="#">关于博主</a></li>
                        <li><a href="#" target="_blank">文档支持</a></li>
                        <li><a href="/blog/">博客首页</a></li>
                    </ul>
                    <p>Copyright © 2019  xls</p>
                </div>
            </div>
        </div>
      </footer>
    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="{% static 'jquery-3.2.1.min.js' %}"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
      <script>
       $("#back-to-top").click(function (){
           window.scrollTo(0,0)
       });
      </script>
    {% block script %}

    {% endblock %}
  </body>
</html>

website/blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load comments %}
{% load static %}
{% block title %}博客详细页面{% endblock %}
{% block css %}
    <link href="{% static 'blog/css/github.css' %}" rel="stylesheet"/>
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class = "col-md-9">
                <h1>{{ entry.title }}</h1>
                <p>
                    <strong>{{ entry.author }}</strong>
                    &nbsp;&nbsp;&nbsp;&nbsp;{{ entry.created_time|date:'Y年m月d日'}}
                    &nbsp;&nbsp;&nbsp;&nbsp;分类:
                    {% for category in entry.category.all %}
                        &nbsp;&nbsp;<a href="{% url 'blog:blog_category' category.id  %}">{{ category.name }}</a>
                    {% endfor %}
                    &nbsp;&nbsp;&nbsp;&nbsp;标签:
                    {% for tag in entry.tags.all %}
                        &nbsp;&nbsp;<a href="{% url 'blog:blog_tag' tag.id  %}">{{ tag.name }}</a>
                    {% endfor %}
                    &nbsp;&nbsp;&nbsp;&nbsp;浏览量:
                        &nbsp;&nbsp;{{ entry.visiting }}
                </p>
                {% if entry.img %}
                <div><img src = "{{ entry.img.url }}" alt="博客配图" width="50%" height="50%"/></div>
                {% endif %}
                <hr/>
                <p>
                    {{ entry.body|safe }}
                </p>

                <div class="row">
                <hr/>
                {% get_comment_form for entry as form %}
                {% get_comment_count for entry as comment_count %}
                <h3>评论总数：{{ comment_count }}</h3>
                <hr/>
                </div>

                {# 评论表单  #}
                <div class="row" >
                <form class="form-horizontal" action="{% comment_form_target %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="input_title" class="pull-left control-label"> 评论标题：</label>
                        <div class="col-sm-6">
                            <input class="form-control" name="comment_title" id="input_title" placeholder="请输入标题" required />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="input_comment" class="pull-left control-label">评论内容:</label>
                        <div class="col-sm-6">
                            <textarea style="resize:none;" class="form-control" rows="6" name="comment" id="input_comment" placeholder="在此输入评论" required></textarea>
                        </div>
                    </div>
                    <span style="display: none;">{{ form.honeypot }}</span>
                    {{ form.content_type }}
                    {{ form.object_pk }}
                    {{ form.timestamp }}
                    {{ form.security_hash }}
                    <input type="hidden" name="next" value="{% url 'blog:blog_detail' entry.id %}" />
                    <input name="parent_id" type="hidden" value="-1"/>
                    <input name="level" type="hidden" value="0"/>

                    <div class="form-group col-sm-7">
                        <div class="pull-left" style="margin-left: 68px;">
                            <button type="reset" class="btn btn-default"><span class="glyphicon glyphicon-repeat"></span>&nbsp;&nbsp;重置</button>
                        </div>
                         <div class="pull-right" style="margin-left: 12px;">
                            <button type="submit" class="btn btn-success" id="id_submit"><span class="glyphicon glyphicon-send"></span>&nbsp;&nbsp;提交</button>
                        </div>
                    </div>
                </form>
                </div>

            {# 评论显示区 #}
            {% for comment in comment_list %}
                <div class="single_comment" style="margin-left: {{ comment.level }}em">
                    <div>
                        {% if comment.user_img %}
                            <img src="{{ comment.user_img }}" alt="user_image" >
                        {% else %}
                            <img src="{% static 'blog/images/adminlogo.jpg' %}"/>
                        {% endif %}
                    </div>

                    <div class="col-md-11 comment-content" style="margin-bottom: 10px;">
                        <strong>{{ comment.comment_title }}</strong>
                        <div>
                            {% if comment.parent_comment %}
                                    {{ comment.user_name }}{{ request.user }}
                                    <i class="glyphicon glyphicon-share-alt"></i>
                                    {{ comment.parent_comment.user_name }}{{ request.user }}
                            {% else %}
                                By&nbsp;&nbsp;
                                    {{ comment.user_name }}{{ request.user }}
                                &nbsp;&nbsp;&nbsp;On&nbsp;&nbsp;
                            {% endif %}
                            <em>{{ comment.submit_date }}</em>
                            {% if request.session.login or request.user.is_authenticated %}
                            &nbsp;&nbsp;&nbsp;<a href="{% url 'blog:comment_reply' comment.id %}">回复</a>
                            {% endif %}
                        </div>
                        <br/>
                        <p>{{ comment.comment }}</p>
                    </div>
                </div>
            {% endfor %}
            </div>
            <div class = "col-md-3">
                {% block toc %}
                     <div class="row">
                        <div class="widgt">
                            <h3>博客目录:</h3>
                            {{ entry.toc|safe }}
                        </div>
                     </div>
                    <hr/>
                {% endblock %}
            {% include 'blog/right_side_bar.html' %}
            </div>
        </div>
    </div>
{% endblock %}

website/blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block title %}登录{% endblock %}
{% block css %}<link href="{% static 'blog/css/login.css' %}" rel="stylesheet"/> {% endblock %}

{% block content %}
    <div class="container">
        <div class="col-md-4 col-md-offset-4">
          <form class='form-login' method="post">
              {% if message %}
              <div class="alert alert-warning">{{ message }}</div>
              {% endif %}
              {% csrf_token %}
          <h2 class = 'text-center'>欢迎登录</h2>
          {{ login_form }}
          <button type="reset" class="btn btn-default pull-left">重置</button>
          <button type="submit" class="btn btn-primary pull-right">提交</button>
          </form>
        </div>
    </div>
{% endblock %}

website/blog/templates/blog/right_side_bar.html
{% load blog_tags %}
    {% block toc %}{% endblock %}
    <div class = "row">
        <div class="widget">
            <h3>最新博客：</h3>
            {% get_recent_entries as recent_entry_list %}

            {% for entry in recent_entry_list %}
                <div>
                    <a href="{{ entry.get_absolute_url }}">{{ entry.title }}</a>
                    <div>{{ entry.author }}  发表于: {{ entry.created_time|date:"Y年m月d日" }}</div>
                </div>
            {% endfor %}
        </div>
    </div>
    <hr/>
    <div class = "row">
        <div class="widget">
            <h3>推荐博客：</h3>
            {% get_popular_entries as popular_entry_list %}

            {% for entry in popular_entry_list %}
                <div>
                    <a href="{{ entry.get_absolute_url }}">{{ entry.title }}</a>
                    <span class="badge" style="color: white ; background-color: deepskyblue" >{{ entry.visiting }}</span>
                </div>
            {% endfor %}
        </div>
    </div>
    <hr/>
    <div class = "row">
        <div class="widget">
            <h3>分类：</h3>
            {% get_categories as category_list %}
            <ul class="list-group">
            {%for category in category_list %}
                <li class="list-group-item">
                    <a href="{% url 'blog:blog_category' category.id %}">{{ category.name }}</a>
                    <span class="badge">{% get_entry_count_of_category category.name  %}</span>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>
    <hr/>
    <div class = "row">
        <div class="widget">
            <h3>归档：</h3>
            {% archives as date_list %}
            <ul class="list-group">
            {%for date in date_list %}
                <li class="list-group-item">
                    <a href="{% url 'blog:blog_archives' date.year date.month%}">
                        <i class="glyphicon glyphicon-chevron-right"></i>
                        {{ date.year }} 年 {{ date.month }} 月
                        <span class="badge">{% get_entry_count_of_date date.year date.month %}</span>
                    </a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>
    <hr/>
    <div class = "row">
        <div class="widget">
            <h3>标签云：</h3>
            {% get_tags as tag_list %}
            {% for tag in tag_list %}
                    <a href="{% url 'blog:blog_tag' tag.id %}">
                        <span class="label {% cycle 'label-default' 'label-primary' 'label-success' 'label-info' 'label-warning' 'label-danger' %}">{{ tag.name }}</span>
                    </a>
            {% endfor %}
        </div>
    </div>
    <hr/>
    <div class="row">
        <div class ="rss">
            <a href="/latest/feed/"><i class="glyphicon glyphicon-globe">RSS订阅</i>   </a>
        </div>
    </div>

website/blog/templates/blog/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="refresh" content="2;url=http://www.baidu.com/" />
    <title>Title</title>
</head>
<body>

</body>
</html>